load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

## google test dependency
http_archive(
  name = "gtest",
  urls = ["https://github.com.cnpmjs.org/google/googletest/archive/refs/tags/release-1.11.0.zip"],
  strip_prefix = "googletest-release-1.11.0",
)
## google benchmark dependency
http_archive(
  name = "gbench",
  urls = ["https://github.com.cnpmjs.org/google/benchmark/archive/refs/tags/v1.6.0.zip"],
  strip_prefix = "benchmark-1.6.0",
  sha256 = "3da225763533aa179af8438e994842be5ca72e4a7fed4d7976dc66c8c4502f58"
)
## protobuf dependency
http_archive(
    name = "rules_proto",
    sha256 = "66bfdf8782796239d3875d37e7de19b1d94301e8972b3cbd2446b332429b4df1",
    strip_prefix = "rules_proto-4.0.0",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/refs/tags/4.0.0.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/refs/tags/4.0.0.tar.gz",
    ],
)
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()


### gRPC Rules for Bazel
http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com.cnpmjs.org/grpc/grpc/archive/11f00485aa5ad422cfe2d9d90589158f46954101.tar.gz",
    ],
    strip_prefix = "grpc-11f00485aa5ad422cfe2d9d90589158f46954101",
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
# Not mentioned in official docs... mentioned here https://github.com/grpc/grpc/issues/20511
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()